[package]
name = "engine"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]

[dependencies]
configuration = { path = "../configuration" }
encryption = { path = "../encryption" }
engine_traits = { path = "../engine_traits" }
hex = "0.4"
lazy_static = "1.3"
prometheus = { version = "0.8", features = ["nightly", "push", "process"] }
protobuf = "2.8"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
sysinfo = { git = "https://github.com/tikv/sysinfo.git", branch = "tikv"}
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
time = "0.1"

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"
features = ["static_libcpp"]

[dev-dependencies]
tempfile = "3.0"
toml = "0.4"
