[package]
name = "tidb_query_common"
version = "0.0.1"
edition = "2018"
publish = false
description = "Common utility of a query engine to run TiDB pushed down executors"

[dependencies]
hex = "0.3"
time = "0.1"
failure = "0.1"
derive_more = "0.99.3"
tikv_util = { path = "../tikv_util" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
prometheus = { version = "0.8", features = ["nightly", "push"] }
lazy_static = "1.3"

[dependencies.prometheus-static-metric]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "fd122caa03de8e7e5e4fae9372583aebf19e39f6"

[dev-dependencies]
byteorder = "1.2"

